spring:
  application:
    name: period-log-service
  main:
    banner-mode: off

  # Database configuration (PostgreSQL)
  datasource:
    url: ${POSTGRES_DB_URL}
    username: ${POSTGRES_DB_USERNAME}
    password: ${POSTGRES_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # JPA Hibernate configuration
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

# JWT
app:
  jwt-secret: ${JWT_SECRET}
  jwt-expiration-milliseconds: ${JWT_EXPIRATION}

server:
  port: 9092

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/